### ISSUE TITLE
MouseDown action fires MouseUp as well

### ISSUE THREAD

**Issue by Zyxil** [LogicalError/Graph#1]
Added this to test how focusing works:

'''
//in ExampleForm()
            graphControl.MouseUp += new MouseEventHandler(graphControl_MouseUp);

//elsewhere
        void graphControl_MouseUp(object sender, MouseEventArgs e)
        {
             SystemSounds.Beep.Play();
            if (graphControl.FocusElement != null)
                lblFocus.Text = graphControl.FocusElement.ToString();
            else
                lblFocus.Text = string.Empty;

```
    }
```

'''

When you click and hold, you will hear a beep, and another when you let go.

**Comment by LogicalError** [comment]
Thanks & it's fixed now :)
It had to do with the event delegates being called before the actual work had been done.
