### ISSUE TITLE
After GraphControl.Click is fired, FocusElement is inconsistent

### ISSUE THREAD

**Issue by Zyxil** [LogicalError/Graph#2]
// in ExampleForm()
            graphControl.Click+=new EventHandler(graphControl_Click);

// elsewhere
        void graphControl_Click(object sender, EventArgs e)
        {
            SystemSounds.Beep.Play();
            if (graphControl.FocusElement != null)
                lblFocus.Text = graphControl.FocusElement.ToString();
            else
                lblFocus.Text = string.Empty;
        }

You will see that the value of FocusElement will not be correct.  NodeSelection when nothing is active or selected.  Node after  clicking away from a node to deselect it.

**Comment by LogicalError** [comment]
Thanks & it's fixed now :)
It had to do with the event delegates being called before the actual work had been done.
