### ISSUE TITLE
GraphControl.Disconnect fires ConnectionRemoved before removing the connection

### ISSUE THREAD

**Issue by Zyxil** [LogicalError/Graph#3]
This should be two events:
- ConnectionRemoving should fire when the current Removed event fires and have the Cancel option
- ConnectionRemoved should fire after the connection has been disconnected.  The eventArgs should give the From and To NodeConnector objects.

**Comment by Zyxil** [comment]
Here's what I did:

NodeConnection.cs:
    public sealed class NodeDisconnectionEventArgs : EventArgs
    {
        public NodeDisconnectionEventArgs(NodeConnector from, NodeConnector to)
        { From = from; To = to; }
        public NodeConnector From { get; private set; }
        public NodeConnector To { get; private set; }
    }

GraphControl.cs:
        public event EventHandler<AcceptNodeConnectionEventArgs> ConnectionRemoving;
        public event EventHandler<NodeDisconnectionEventArgs> ConnectionRemoved;

```
    public bool Disconnect(NodeConnection connection)
    {
        if (connection == null)
            return false;

        if (ConnectionRemoving != null)
        {
            var eventArgs = new AcceptNodeConnectionEventArgs(connection);
            ConnectionRemoving(this, eventArgs);
            if (eventArgs.Cancel)
                return false;
        }

        if (HasFocus(connection))
            FocusElement = null;

        var from = connection.From;
        var to = connection.To;
        if (from != null && from.Node != null)
            from.Node.connections.Remove(connection);
        if (to != null && to.Node != null)
            to.Node.connections.Remove(connection);

        if (ConnectionRemoved != null)
        {
            var eventArgs = new NodeDisconnectionEventArgs(from, to);
            ConnectionRemoved(this, eventArgs);
        }

        // Just in case somebody stored it somewhere ..
        connection.From = null;
        connection.To = null;
        return true;
    }
```

**Comment by LogicalError** [comment]
Thanks for the suggestion! It's implemented now.
